export const techStack = [
  { name: "HTML", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
  { name: "CSS", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
  { name: "JavaScript", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
  { name: "Python", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" },
  { name: "Java", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" },
  { name: "React", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
  { name: "Node.js", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg" },
  { name: "Express.js", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg" },
  { name: "MongoDB", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg" },
  { name: "SQL", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" },
  { name: "Git", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg" },
  { name: "GitHub", logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" },
  { name: "Vercel", logo: "https://assets.vercel.com/image/upload/front/favicon/vercel/180x180.png" },
];

export const learningPath = [
  {
    title: "React Basics",
    channel: "freeCodeCamp",
    link: "https://www.youtube.com/watch?v=bMknfKXIFA8",
    image: "https://img.youtube.com/vi/bMknfKXIFA8/0.jpg",
  },
  {
    title: "Tailwind CSS",
    channel: "Traversy Media",
    link: "https://www.youtube.com/watch?v=dFgzHOX84xQ",
    image: "https://img.youtube.com/vi/dFgzHOX84xQ/0.jpg",
  },
  {
    title: "Node.js Crash Course",
    channel: "Traversy Media",
    link: "https://www.youtube.com/watch?v=fBNz5xF-Kx4",
    image: "https://img.youtube.com/vi/fBNz5xF-Kx4/0.jpg",
  },
  {
    title: "React Basics",
    channel: "freeCodeCamp",
    link: "https://www.youtube.com/watch?v=bMknfKXIFA8",
    image: "https://img.youtube.com/vi/bMknfKXIFA8/0.jpg",
  },
  {
    title: "Tailwind CSS",
    channel: "Traversy Media",
    link: "https://www.youtube.com/watch?v=dFgzHOX84xQ",
    image: "https://img.youtube.com/vi/dFgzHOX84xQ/0.jpg",
  },
  {
    title: "Node.js Crash Course",
    channel: "Traversy Media",
    link: "https://www.youtube.com/watch?v=fBNz5xF-Kx4",
    image: "https://img.youtube.com/vi/fBNz5xF-Kx4/0.jpg",
  },
  {
    title: "React Basics",
    channel: "freeCodeCamp",
    link: "https://www.youtube.com/watch?v=bMknfKXIFA8",
    image: "https://img.youtube.com/vi/bMknfKXIFA8/0.jpg",
  },
  {
    title: "Tailwind CSS",
    channel: "Traversy Media",
    link: "https://www.youtube.com/watch?v=dFgzHOX84xQ",
    image: "https://img.youtube.com/vi/dFgzHOX84xQ/0.jpg",
  },
  {
    title: "Node.js Crash Course",
    channel: "Traversy Media",
    link: "https://www.youtube.com/watch?v=fBNz5xF-Kx4",
    image: "https://img.youtube.com/vi/fBNz5xF-Kx4/0.jpg",
  },
  {
    title: "React Basics",
    channel: "freeCodeCamp",
    link: "https://www.youtube.com/watch?v=bMknfKXIFA8",
    image: "https://img.youtube.com/vi/bMknfKXIFA8/0.jpg",
  },
  {
    title: "Tailwind CSS",
    channel: "Traversy Media",
    link: "https://www.youtube.com/watch?v=dFgzHOX84xQ",
    image: "https://img.youtube.com/vi/dFgzHOX84xQ/0.jpg",
  },
  {
    title: "Node.js Crash Course",
    channel: "Traversy Media",
    link: "https://www.youtube.com/watch?v=fBNz5xF-Kx4",
    image: "https://img.youtube.com/vi/fBNz5xF-Kx4/0.jpg",
  },
];
